version: '3'

services:
  octoprint:
    build: ./octoprint
    container_name: octoprint
    restart: always
    volumes:
      - ophome:/home/octoprint
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  proxy:
    image: caddy:alpine
#     image: nginx:1-alpine
    container_name: proxy
    restart: always
    depends_on:
      - octoprint
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/usr/local/etc/certs:ro
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  ophome:
    name: "octoprint_home"
