version: '3'

services:
  octoprint:
    build: ./octoprint
    container_name: octoprint
    restart: always
    volumes:
      - ophome:/home/octoprint
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

#   nginx:
#     image: nginx:1-alpine
#     container_name: nginx
#     restart: always
#     depends_on:
#       - octoprint
#     ports:
#       - 80:80
#       - 443:443
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  proxy:
    image: caddy:alpine
    container_name: caddy
    restart: always
    depends_on:
      - octoprint
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/usr/local/etc/certs:ro

volumes:
  ophome:
