version: '3'

services:
  octoprint:
    build:
      context: ./octoprint
      tags:
        - "octoprint:python3.10-alpine"
    container_name: octoprint
    restart: always
    volumes:
      - ophome:/home/octoprint
#     devices:
#       - /dev/ttyACM0:/dev/ttyACM0 # Printer connection

  proxy:
    image: caddy:alpine
#     image: nginx:1-alpine
    container_name: proxy
    restart: always
    depends_on:
      - octoprint
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/usr/local/etc/certs:ro
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  camera:
  # H/T: https://community.octoprint.org/t/using-libcamera-with-octoprint-the-docker-way/43951
    build:
      context: ./camera-streamer
      tags:
        - "camera-streamer:bullseye-slim"
    container_name: camera
    privileged: true
    restart: always
    command: ["--camera-type=libcamera", "--camera-format=YUYV", "--camera-width=2304", "-camera-height=1296", "--camera-fps=30", "--camera-nbufs=2", "--camera-snapshot.height=1080", "--camera-video.height=720", "--camera-stream.height=480", "--camera-options=AfMode=2", "--camera-options=AfRange=2"]
    volumes:
      - /run/udev:/run/udev:ro

volumes:
  # Persistent volume for OctoPrint data and installation
  ophome:
    name: "octoprint_home"
