version: '3'

services:
  octoprint:
    build: ./octoprint
    container_name: octoprint
    restart: always
    volumes:
      - ./data/:/home/octoprint/.octoprint/
#      - ./data/static:/home/octoprint/.local/lib/python3.10/site-packages/octoprint/static/

#   nginx:
#     image: nginx:1-alpine
#     container_name: nginx
#     restart: always
#     depends_on:
#       - octoprint
#     ports:
#       - 80:80
#       - 443:443
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: always
    restart: always
    depends_on:
      - octoprint
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
